user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    client_max_body_size 20m;
# Rate limit zones (per client IP)
    limit_req_zone $binary_remote_addr zone=login_zone:10m rate=5r/m;
    limit_req_zone $binary_remote_addr zone=register_zone:10m rate=3r/m;
    limit_req_zone $binary_remote_addr zone=api_zone:10m rate=30r/s;
    limit_conn_zone $binary_remote_addr zone=livelink_conn:10m;
    limit_req_zone  $binary_remote_addr zone=livelink_req:10m rate=5r/s;

    map $http_origin $livelink_origin_ok {
        default 0;
        "" 1;  # tillad klienter uden Origin (fx websocat)

        "https://www.isbaksoftware.dk" 1;
        "https://isbaksoftware.dk" 1;
    }
    include /etc/nginx/conf.d/*.conf;
}

